apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edge
  name: edge
spec:
  replicas: {{ default 2 .Values.edgeNode.replicas }}
  selector:
    matchLabels:
      io.kompose.service: edge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: edge
    spec:
      containers:
        - name: edge
          {{- $imageTag := default .Values.global.imageTagNodes .Values.edgeNode.imageTag }}
          image: {{ printf "%s/%s:%s" .Values.global.repository .Values.edgeNode.imageName $imageTag }}
          imagePullPolicy: {{ .Values.edgeNode.imagePullPolicy }}
          env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            {{- range .Values.edgeNode.extraEnvironmentVariables }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          ports:
            - containerPort: 5900
          {{- with .Values.edgeNode.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ default "2Gi" .Values.edgeNode.dshmVolumeSizeLimit }}
status: {}
