apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: firefox
  name: firefox
spec:
  replicas: {{ default 2 .Values.firefoxNode.replicas }}
  selector:
    matchLabels:
      io.kompose.service: firefox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: firefox
    spec:
      containers:
        - name: firefox
          {{- $imageTag := default .Values.global.imageTag .Values.firefoxNode.imageTag }}
          image: {{ printf "%s/%s:%s" .Values.global.repository .Values.firefoxNode.imageName $imageTag }}
          imagePullPolicy: {{ .Values.firefoxNode.imagePullPolicy }}
          # environment variables
          {{- with .Values.hub.extraEnvironmentVariables }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5900
          {{- with .Values.firefoxNode.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: {{ default "2Gi" .Values.firefoxNode.dshmVolumeSizeLimit }}
status: {}
