apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium-hub
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: selenium-hub
    spec:
      containers:
        - name: selenium-hub
          {{- $imageTag := default .Values.global.imageTag .Values.hub.imageTag }}
          image: {{ printf "%s/%s:%s" .Values.global.repository .Values.hub.imageName $imageTag }}
          imagePullPolicy: {{ .Values.hub.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.hub.port }}
              protocol: TCP
            - containerPort: {{ .Values.hub.publishPort }}
              protocol: TCP
            - containerPort: {{ .Values.hub.subscribePort }}
              protocol: TCP
          {{- with .Values.hub.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.hub.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.hub.livenessProbe.path }}
              port: {{ .Values.hub.port }}
            initialDelaySeconds: {{ .Values.hub.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hub.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hub.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.hub.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.hub.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.hub.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.hub.readinessProbe.path }}
              port: {{ .Values.hub.port }}
            initialDelaySeconds: {{ .Values.hub.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.hub.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.hub.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.hub.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.hub.readinessProbe.failureThreshold }}
          {{- end }}
          # environment variables
          {{- with .Values.hub.extraEnvironmentVariables }}
          env: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
      restartPolicy: Always
status: {}
