apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: chrome
  name: chrome
spec:
  ports:
    - name: "6900"
      port: 6900
      targetPort: 5900
  selector:
    io.kompose.service: chrome
status:
  loadBalancer: {}
