apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edge
  name: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: edge
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: edge
    spec:
      containers:
        - env:
            - name: SE_EVENT_BUS_HOST
              value: selenium-hub
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          image: selenium/node-edge:4.0.0
          name: edge
          ports:
            - containerPort: 5900
          resources: {}
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      restartPolicy: Always
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
status: {}
