apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-grid
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: selenium-grid.integ.sehlat.io
    http:
      paths:
      - backend:
          service:
            name: selenium-hub
            port:
              number: 4444
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - selenium-grid.integ.sehlat.io
    secretName: tls-certificate
