global: 
  repository: integ.docker.pkg.sehlat.io
  imageTagNodes: 4.0.0

imagePullSecrets:
  - name: integ-registry

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: seleniumgrid.grid.integ.sehlat.io
      paths:
        - /
  tls:
    - secretName: selenium-grid-tls
      hosts:
        - seleniumgrid.dev.integ.sehlat.io


# configuration for hub 
hub: 
  imageName: selenium/hub
  imageTag: 4.0.0
  imagePullPolicy: IfNotPresent
  livenessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1

  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "300"
    - name: SE_OPTS
      value: "--log-level FINE"

# configuration for node chrome
chromeNode:
  enabled: true
  imageTag: 4.0.0
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

# configuration for edge chrome
edgeNode:
  enabled: true  
  imageTag: 4.0.0
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
  dshmVolumeSizeLimit: 2Gi

# configuration for node firefox
firefoxNode:
  enabled: true
  imageTag: 4.0.0
  replicas: 1
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
  dshmVolumeSizeLimit: 2Gi

