# general
global: 
  repository: "#{repository}"
  imageTagNodes: "#{imageTag}"

ingress:
  enabled: true
  annotations: 
     cert-manager.io/common-name: "#{host}"
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: "#{host}"

  tls:
    - secretName: seleniumgrid-tls
      hosts:
        - "#{host}"

# hub 
hub: 
  imageName: selenium/hub
  imageTag: 4.0.0
  imagePullPolicy: IfNotPresent
  port: 4444
  publishPort: 4442
  subscribePort: 4443

  livenessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1

  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "300"
    - name: SE_OPTS
      value: "--log-level FINE"

# node chrome
chromeNode:
  imageName: selenium/node-chrome
  enabled: true
  imageTag: 4.0.0
  replicas: 10
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "#{NODE.REQ.MEM}"
      cpu: "#{NODE.REQ.CPU}"
    limits:
      memory: "#{NODE.LIM.MEM}"
      cpu: "#{NODE.LIM.CPU}"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

# edge chrome
edgeNode:
  enabled: true
  imageName: selenium/node-edge
  imageTag: 4.0.0
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "#{NODE.REQ.MEM}"
      cpu: "#{NODE.REQ.CPU}"
    limits:
      memory: "#{NODE.LIM.MEM}"
      cpu: "#{NODE.LIM.CPU}"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

# node firefox
firefoxNode:
  enabled: true
  imageName: selenium/node-firefox
  imageTag: 4.0.0
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "#{NODE.REQ.MEM}"
      cpu: "#{NODE.REQ.CPU}"
    limits:
      memory: "#{NODE.LIM.MEM}"
      cpu: "#{NODE.LIM.CPU}"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

