# general
global: 
  repository: integ.docker.pkg.sehlat.io
  imageTag: 4.0.0

imagePullSecrets:
  - name: integ-registry

ingress:
  enabled: true
  annotations: 
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  hosts:
    - host: seleniumgrid.dev.integ.sehlat.io

  tls:
    - secretName: seleniumgrid-tls
      hosts:
        - seleniumgrid.dev.integ.sehlat.io

# hub
hub: 
  imageName: selenium/hub
  imagePullPolicy: IfNotPresent
  port: 4444
  publishPort: 4442
  subscribePort: 4443

  livenessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 10
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    path: /wd/hub/status
    initialDelaySeconds: 12
    failureThreshold: 10
    timeoutSeconds: 10
    periodSeconds: 10
    successThreshold: 1

  extraEnvironmentVariables:
    - name: SE_SESSION_REQUEST_TIMEOUT
      value: "300"
    - name: SE_OPTS
      value: "--log-level FINE"

# node chrome
chromeNode:
  enabled: true
  imageName: selenium/node-chrome
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

# edge chrome
edgeNode:
  enabled: true
  imageName: selenium/node-edge
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

# node firefox
firefoxNode:
  enabled: true
  imageName: selenium/node-firefox
  replicas: 2
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"
  extraEnvironmentVariables:
    - name: SE_OPTS
      value: "--log-level FINE"
  dshmVolumeSizeLimit: 2Gi

